Revert plugins
opentdf/backend-go pull request #57
Opened 2024-01-03 15:29 UTC by krokhmaliuk-virtru

Reverted previous merged PR with plugins
https://github.com/opentdf/backend-go/pull/22/files

2024-01-10 14:53 UTC, dmihalcik-virtru requested changes
Can you add a link to the commit(s) you are reverting to the PR description please?

2024-01-10 14:53 UTC, dmihalcik-virtru commented on pkg/access/rewrap.go
> +	handleContentLength(w, r)
This won't escape the Handler so you'll need to revert it. Don't worry about the 'function too long' linter; it does not block the merge

2024-01-10 16:24 UTC, krokhmaliuk-virtru commented on pkg/access/rewrap.go
> +	handleContentLength(w, r)
get it, done

2024-01-10 18:40 UTC, dmihalcik-virtru submitted a review, later dismissed

2024-01-11 09:06 UTC, sievdokymov-virtru approved these changes

2024-01-11 09:28 UTC, merged